import os, re

# -----------------------------------| TWM SETTINGS |----------------------------------- #

MOD 	= "mod4"
FONT 	= "FiraCode Nerd Font" 	# Do not use Mono. Because icons will appears as too small.
TERM	= "alacritty" 			# Not used for now

# Keys to use for accessing groups
KEYBOARD_GROUP_SHORTCUT = {
	1:"ampersand", 
	2:"eacute", 
	3:"quotedbl", 
	4:"apostrophe", 
	5:"parenleft", 
	6:"minus", 
	7:"egrave", 
	8:"underscore", 
	9:"ccedilla", 
	10:"agrave"
}


# -----------------------------------| COLOR SCHEME |----------------------------------- #

colors = {
	"white"			: "#d3d7cf",
	"light_white"	: "#e5e9f0",
	"black"			: "#242831",
	"light_black"	: "#2e3436",
	"red"			: "#ef2929",
	"light_red"		: "#bf616a",
	"blue"		 	: "#3465a4",	
	"light_blue"	: "#81a1c1",	
	"cyan" 			: "#f57900",	
	"light_cyan"	: "#fcaf3e",	
	"green"			: "#8ae234",
	"light_green"	: "#a3be8c",
	"yellow"		: "#edd400",
	"light_yellow"	: "#ebcb8b",
	"magenta"		: "#75507b",
	"light_magenta" : "#b48ead",
	"transparent"	: "#00000000"
}


# --------------------------------------| CACHE |--------------------------------------- #

PATH_CACHE 			= "~/.local/share/qtile/"
PATH_ICONS_CACHE	= os.path.expanduser(PATH_CACHE + "icons")
PATH_LAYOUT_ICONS	= os.path.expanduser("~/.config/qtile/DATA/icons")


# ---------------------------------------| FONT |--------------------------------------- #

# All icon's code points from the chosen font. Font change may impact this.
# E.g for Nerd Font Fire Code, link here:
# https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
DICT_CODE_POINT = {
		"Custom_Seti-UI":       (0xe5fa, 0xe631),
		"Devicons":             (0xe700, 0xe7c5),
		"Awesome":              (0xf000, 0xf2e0),
		"Awesome_Extension":	(0xe200, 0xe2a9),
		"Material_Design":      (0xf500, 0xfd46),
		"Weather":              (0xe300, 0xe3eb),
		"Octicons":             (0xf400, 0xf4a9),
		"Octicons2":			(0x2665, 0x26a1),
		"Powerline":            (0xe0a0, 0xe0a2),
		"Powerline2":           (0xe0b0, 0xe0b3),
		"Powerline_Extra":		(0xe0a3, 0xe0a3),
		"Powerline_Extra2":		(0xe0b4, 0xe0c8),
		"Powerline_Extra3":		(0xe0ca, 0xe0ca),
		"Powerline_Extra4":		(0xe0cc, 0xe0d4),
		"IEC_Power_Symbols":    (0x23fb, 0x23fe),
		"IEC_Power_Symbols2":   (0x2b58, 0x2b58),
		"Font_Linux":           (0xf300, 0xf32d),
		"Pomicons":             (0xe000, 0xe00a),
		"Codicons":             (0xea60, 0xebeb)
}


# -----------------------------------| SKETCHY APPS |----------------------------------- #

# Apps spawning on the wrong groups (startup only)
# Use `xprop` utility and look for `WM_NAME`, example:
DICT_SKETCHY_APPS_ONCE  = {"VSCodium": ""}

# Same as before, but not only on startup. 
# Same principle but use a compiled regex expression as key
DICT_MATCH = {
	# For Virtual Box dual screen
	re.compile(".* - Oracle VM VirtualBox : 2.*"): "icon",	
	re.compile(".* - Oracle VM VirtualBox : 1.*"): ""
}


# ------------------------------------| WALLPAPER |------------------------------------- #

# Switch from one wallpaper folder to another. Files can be found in `.config/wallpaper`
LIST_WALLPAPER_MODES 	= ["default", "real"]
PATH_WALLPAPER_SCRIPT	= os.path.expanduser("~/.config/wallpaper/script.sh")


# ------------------------------| ENCYCLOPEDIA GALACTICA |------------------------------ #

# Path to Encyclopedia Galactica. Optional
PATH_ENCYCLOPEDIA = "/mnt/data/Encyclopedia\ Galactica/"

# ------------------------------------| AUTOSTART |------------------------------------- #

# Path to autostart script 
PATH_AUTOSTART = os.path.expanduser("~/.config/qtile/autostart.sh")


# ------------------------------------| SOUND SINK |------------------------------------ #

# Sink name found manually. Did that once for and for all.
SOUND_SINK_NAME = "alsa_output.usb-Logitech_PRO_X_000000000000-00.analog-stereo"

# -------------------------------------| Screens |-------------------------------------- #

# Not use for now

AVAILABLE_SCREENS = {
	"primary": "DP-4",
	"secondary": "HDMI-0"
}

# --------------------------------------| DEBUG |--------------------------------------- #

# Log prefix, to spot more easily log generated by this config
LOG_PREFIX = "[CONFIG LOG]"

